site_name: 'Erick Sang Data Engineering Docs'
theme:
  name: 'material'
  logo: docs/assets/images/logo.png
  favicon: docs/assets/images/favicon.png
  palette:
    - scheme: default
      primary: teal
      accent: lime
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.code.annotate
    - content.tabs.link
plugins:
  - search
  - mkdocs-jupyter
nav:
  - Home: index.md
  - Notebooks: notebooks.md
  - Topics:
      - Data Engineering: data-engineering.md
      - Cloud: cloud.md
      - Python: python.md
      - SQL: sql.md
      - Airflow: airflow.md
      - Databricks: databricks.md
      - BI & Visualization: bi.md
      - Kafka: kafka.md
      - dbt: dbt.md
      - Spark: spark.md
      - Others: others.md
repo_url: 'https://github.com/Leonsang/Leonsang'
repo_name: 'Leonsang/Leonsang'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/esangc
    - icon: fontawesome/brands/github
      link: https://github.com/Leonsang
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ericksang
